[wokwi]
version = 1
firmware = ".pio/build/ttgo-lora32-v21/firmware.bin"
elf     = ".pio/build/ttgo-lora32-v21/firmware.elf"

[net]
enabled = false   # 네트워크 불필요, 시뮬레이션 속도 향상

[[monitor]]
speed = 115200    # Serial 보드레이트와 일치